[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
57054 = "${RPC_URL}"

[etherscan]
57054 = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.sonicscan.org/api" }